# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.py'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
def f():
    l1 = input().split(' ')
    a = int(l1[0])
    b = int(l1[1])
    x = int(l1[2])+1
    y = int(l1[3])+1
    m = max((a - x) * b, (x - 1) * b, (b - y) * a, (y - 1) * a)
    print(m)
    return 0


row = int(input())
for r in range(row):
    f()

  		  	 		  	   	 	 			  		 		