import json
from pathlib import Path

path = Path(r"d:/ML/Codeforces_RL_Recommender.ipynb")
nb = json.loads(path.read_text(encoding="utf-8"))

phrase_replacements = {
    "Load and Explore Codeforces Datasets": "Tải và khám phá dữ liệu Codeforces",
    "Data Merging and Preprocessing": "Gộp dữ liệu và tiền xử lý",
    "Feature Engineering": "Trích xuất đặc trưng",
    "Environment Implementation": "Xây dựng môi trường",
    "Q-Learning Agent Implementation": "Cài đặt tác tử Q-Learning",
    "Training Q-Learning Agent": "Huấn luyện tác tử Q-Learning",
    "Baseline Policies": "Các chính sách baseline",
    "Evaluation and Comparison": "Đánh giá và so sánh",
    "Visualization and Analysis": "Trực quan hóa và phân tích",
    "Recommendation System": "Hệ thống gợi ý",
    "Summary and Conclusions": "Tổng kết và kết luận",
    "Quick Reference & Use Cases": "Hướng dẫn nhanh và tình huống sử dụng",
    "Report Presentation Content": "Nội dung thuyết trình báo cáo",
    "Executive Summary": "Tóm tắt điều hành",
    "Research Objective": "Mục tiêu nghiên cứu",
    "Dataset and Preprocessing": "Dữ liệu và tiền xử lý",
    "Experimental Design": "Thiết kế thí nghiệm",
    "Evaluation Metrics": "Chỉ số đánh giá",
    "Main Findings": "Kết quả chính",
    "Limitations": "Hạn chế",
    "Practical Implications": "Ý nghĩa thực tiễn",
    "Conclusion": "Kết luận",
    "Loading Codeforces Problems dataset": "Đang tải dữ liệu bài toán Codeforces",
    "Codeforces Problems Dataset": "Bộ dữ liệu bài toán Codeforces",
    "Shape": "Kích thước",
    "Columns": "Các cột",
    "First few rows": "Một vài dòng đầu",
    "Data types": "Kiểu dữ liệu",
    "Missing values": "Giá trị thiếu",
    "Loading Codeforces Submissions dataset": "Đang tải dữ liệu bài nộp Codeforces",
    "Loaded {len(submissions_data)} submissions (sample)": "Đã tải {len(submissions_data)} bài nộp (mẫu)",
    "Submissions DataFrame": "DataFrame bài nộp",
    "No submissions loaded. Creating synthetic dataset for demo": "Không tải được bài nộp. Tạo dữ liệu giả lập để demo",
    "Creating synthetic submission data for training": "Đang tạo dữ liệu bài nộp giả lập cho huấn luyện",
    "Synthetic submissions created": "Đã tạo dữ liệu giả lập",
    "records": "bản ghi",
    "Verdicts distribution": "Phân bố kết quả (verdict)",
    "Data Preprocessing": "Tiền xử lý dữ liệu",
    "Problem ratings mapped": "Đã ánh xạ độ khó cho",
    "problems": "bài",
    "Users with >=": "Người dùng có >=",
    "submissions": "bài nộp",
    "out of": "/",
    "Remaining submissions": "Số bài nộp còn lại",
    "Cleaned Dataset Statistics": "Thống kê dữ liệu sau làm sạch",
    "Total submissions": "Tổng số bài nộp",
    "Unique users": "Số người dùng duy nhất",
    "Unique problems": "Số bài toán duy nhất",
    "AC rate": "Tỷ lệ AC",
    "First few cleaned records": "Một vài bản ghi sau làm sạch",
    "Sample User Features": "Ví dụ đặc trưng người dùng",
    "User states calculated for": "Đã tính trạng thái cho",
    "Feature Statistics": "Thống kê đặc trưng",
    "Accuracy - Mean": "Độ chính xác - Trung bình",
    "Streak - Mean": "Chuỗi AC - Trung bình",
    "Rating - Mean": "Rating - Trung bình",
    "Range": "Khoảng",
    "Building Programming Exercise Recommendation Environment": "Đang xây dựng môi trường gợi ý bài luyện tập",
    "Environment created": "Đã tạo môi trường",
    "Rating buckets": "Số bucket rating",
    "Accuracy buckets": "Số bucket độ chính xác",
    "Streak buckets": "Số bucket chuỗi AC",
    "Total states": "Tổng số trạng thái",
    "Problems by difficulty": "Số bài theo mức độ khó",
    "Difficulty": "Độ khó",
    "Implementing Q-Learning Agent": "Đang cài đặt tác tử Q-Learning",
    "Q-Learning agent created": "Đã tạo tác tử Q-Learning",
    "Learning rate": "Tốc độ học",
    "Discount factor": "Hệ số chiết khấu",
    "Initial epsilon": "Epsilon ban đầu",
    "Training Q-Learning Agent with full progress tracking": "Đang huấn luyện Q-Learning với theo dõi tiến trình đầy đủ",
    "Training for": "Huấn luyện trong",
    "Users per episode": "Số người dùng mỗi episode",
    "Avg Reward": "Phần thưởng TB",
    "Success Rate": "Tỷ lệ thành công",
    "Training completed": "Huấn luyện hoàn tất",
    "Final average reward": "Phần thưởng trung bình cuối",
    "Final success rate": "Tỷ lệ thành công cuối",
    "Q-table size": "Kích thước Q-table",
    "unique states visited": "trạng thái duy nhất đã thăm",
    "Episodes tracked": "Số episode đã theo dõi",
    "Total tracked steps": "Tổng số bước đã theo dõi",
    "Implementing Baseline Policies": "Đang cài đặt các chính sách baseline",
    "Baseline policies created": "Đã tạo các chính sách baseline",
    "Training Random Policy": "Đang huấn luyện chính sách ngẫu nhiên",
    "Training Rule-Based Policy": "Đang huấn luyện chính sách theo luật",
    "All baselines trained": "Tất cả baseline đã huấn luyện xong",
    "Evaluating Policy Performance": "Đang đánh giá hiệu năng các chính sách",
    "POLICY PERFORMANCE COMPARISON": "SO SÁNH HIỆU NĂNG CHÍNH SÁCH",
    "Metric": "Chỉ số",
    "Final Reward": "Phần thưởng cuối",
    "Final Accuracy": "Độ chính xác cuối",
    "Q-Learning Improvement over Baselines": "Mức cải thiện của Q-Learning so với baseline",
    "vs Random": "so với Random",
    "vs Rule-Based": "so với Rule-Based",
    "Running demo flow for one low-rating user": "Đang chạy luồng demo cho người dùng mức rating thấp",
    "Demo completed with": "Demo hoàn tất với",
    "steps": "bước",
    "Start rating": "Rating ban đầu",
    "End rating": "Rating cuối",
    "Start accuracy": "Độ chính xác ban đầu",
    "End accuracy": "Độ chính xác cuối",
    "Learning Path Timeline": "Dòng thời gian học tập",
    "Progress Summary": "Tóm tắt tiến bộ",
    "Generating required progression visualizations": "Đang tạo các biểu đồ tiến trình bắt buộc",
    "User Level Progression": "Tiến trình cấp độ người dùng",
    "Accuracy Progression": "Tiến trình độ chính xác",
    "Difficulty vs User Level": "Độ khó so với cấp độ người dùng",
    "Reward Curve (per Episode)": "Đường cong phần thưởng (theo episode)",
    "Q-table Heatmap": "Bản đồ nhiệt Q-table",
    "Q-table Heatmap (State x Action)": "Bản đồ nhiệt Q-table (Trạng thái x Hành động)",
    "Saved": "Đã lưu",
    "Q-Table Analysis": "Phân tích Q-Table",
    "Total unique states explored": "Tổng số trạng thái duy nhất đã khám phá",
    "Q-Value Statistics": "Thống kê Q-Value",
    "Mean": "Trung bình",
    "Std Dev": "Độ lệch chuẩn",
    "Min": "Nhỏ nhất",
    "Max": "Lớn nhất",
    "Median": "Trung vị",
    "Action Preference in Learned Policy": "Ưu tiên hành động trong chính sách đã học",
    "states": "trạng thái",
    "Action Preference Distribution": "Phân bố ưu tiên hành động",
    "Q-Value Distribution": "Phân bố Q-Value",
    "Q-table analysis visualization saved to": "Đã lưu biểu đồ phân tích Q-table vào",
    "Building Recommendation System": "Đang xây dựng hệ thống gợi ý",
    "Recommendation system created": "Đã tạo hệ thống gợi ý",
    "SAMPLE RECOMMENDATIONS FOR DIFFERENT USER TYPES": "VÍ DỤ GỢI Ý CHO CÁC NHÓM NGƯỜI DÙNG",
    "User Type": "Nhóm người dùng",
    "Rating": "Rating",
    "Accuracy": "Độ chính xác",
    "Streak": "Chuỗi AC",
    "Recommendation": "Gợi ý",
    "Q-Values": "Q-Values",
    "Reason": "Lý do",
    "Suggested Problems": "Các bài gợi ý",
    "Problem": "Bài",
    "Preparing Flask API and Chart.js demo": "Đang chuẩn bị Flask API và demo Chart.js",
    "RL Progress Dashboard": "Bảng điều khiển tiến trình RL",
    "Learning Progress Dashboard": "Bảng điều khiển tiến trình học tập",
    "Chart.js line charts for user level and accuracy progression": "Biểu đồ đường Chart.js cho tiến trình cấp độ và độ chính xác",
    "Level Progression Chart": "Biểu đồ tiến trình cấp độ",
    "Accuracy Chart": "Biểu đồ độ chính xác",
    "User Rating": "Rating người dùng",
    "Step": "Bước",
    "API ready": "API sẵn sàng",
    "Chart.js dashboard": "bảng điều khiển Chart.js",
    "Run server manually when needed": "Chạy server thủ công khi cần",
    "FINAL SUMMARY: Q-LEARNING FOR PROGRAMMING EXERCISE RECOMMENDATION": "TỔNG KẾT CUỐI: Q-LEARNING CHO GỢI Ý BÀI LUYỆN TẬP",
    "NOTEBOOK EXECUTION COMPLETED SUCCESSFULLY": "NOTEBOOK ĐÃ CHẠY THÀNH CÔNG",
    "QUICK REFERENCE - Usage Examples": "HƯỚNG DẪN NHANH - Ví dụ sử dụng",
    "Example 1: Get recommendation for a specific user": "Ví dụ 1: Lấy gợi ý cho một người dùng cụ thể",
    "Recommended Difficulty": "Độ khó được gợi ý",
    "Example 2: Get recommendations for multiple users": "Ví dụ 2: Lấy gợi ý cho nhiều người dùng",
    "Generated": "Đã tạo",
    "User": "Người dùng",
    "level": "mức",
    "Example 3: Compare Q-values for policy decisions": "Ví dụ 3: So sánh Q-value cho quyết định chính sách",
    "Q-values represent expected future reward for each action": "Q-value biểu diễn phần thưởng kỳ vọng trong tương lai cho mỗi hành động",
    "Agent chooses": "Tác tử chọn",
    "Example 4: Creating new agent with different parameters": "Ví dụ 4: Tạo tác tử mới với tham số khác",
    "Quick reference examples completed": "Đã hoàn tất ví dụ hướng dẫn nhanh",
}

changes = 0
for cell in nb.get("cells", []):
    src = cell.get("source", [])
    new_src = []
    for line in src:
        new_line = line
        for old, new in phrase_replacements.items():
            if old in new_line:
                new_line = new_line.replace(old, new)
        if new_line != line:
            changes += 1
        new_src.append(new_line)
    cell["source"] = new_src

path.write_text(json.dumps(nb, ensure_ascii=False, indent=4), encoding="utf-8")
print(f"Updated lines: {changes}")
