# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.py'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
n = 0
s = input()
l = []
ppiont = 0
bpiont = len(s)-1
while bpiont > ppiont:
    if s[ppiont] == "(" and s[bpiont] == ")":
        l.append(ppiont)
        l.append(bpiont)
        n += 2
        ppiont += 1
        bpiont -= 1
    if s[ppiont] == ")":
        ppiont += 1
    if s[bpiont] == "(":
        bpiont -= 1
if n == 0:
    print(n)
else:
    print(1)
    print(n)
    l.sort()
    for i in l:
        print(i+1)




 		 	  		     		  	    			   		